#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

mkdir -p constant/triSurface
cp cube.stl constant/triSurface/.

runApplication blockMesh # create the mesh
runApplication checkMesh # check the mesh

runApplication surfaceFeatures # feature extraction 
runApplication snappyHexMesh -overwrite   # snappyHexMesh 
runApplication extrudeMesh # extrude to make a 2D mesh from a 3D one

#------------------------------------------------------------------------------
